%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/lyrical/.*$
%global __requires_exclude_from ^/opt/ros/lyrical/.*$

%global __cmake_in_source_build 1

Name:           ros-lyrical-yasmin-ros
Version:        6.1.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS yasmin_ros package

License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lyrical-example-interfaces
Requires:       ros-lyrical-geometry-msgs
Requires:       ros-lyrical-pluginlib
Requires:       ros-lyrical-rclcpp
Requires:       ros-lyrical-rclcpp-action
Requires:       ros-lyrical-rclpy
Requires:       ros-lyrical-rosidl-runtime-py
Requires:       ros-lyrical-std-msgs
Requires:       ros-lyrical-std-srvs
Requires:       ros-lyrical-tf2
Requires:       ros-lyrical-tf2-msgs
Requires:       ros-lyrical-tf2-py
Requires:       ros-lyrical-tf2-ros
Requires:       ros-lyrical-tf2-ros-py
Requires:       ros-lyrical-yasmin
Requires:       ros-lyrical-ros-workspace
BuildRequires:  ros-lyrical-ament-cmake
BuildRequires:  ros-lyrical-ament-cmake-python
BuildRequires:  ros-lyrical-example-interfaces
BuildRequires:  ros-lyrical-geometry-msgs
BuildRequires:  ros-lyrical-pluginlib
BuildRequires:  ros-lyrical-rclcpp
BuildRequires:  ros-lyrical-rclcpp-action
BuildRequires:  ros-lyrical-rclpy
BuildRequires:  ros-lyrical-ros-environment
BuildRequires:  ros-lyrical-std-msgs
BuildRequires:  ros-lyrical-std-srvs
BuildRequires:  ros-lyrical-tf2
BuildRequires:  ros-lyrical-tf2-msgs
BuildRequires:  ros-lyrical-tf2-py
BuildRequires:  ros-lyrical-tf2-ros
BuildRequires:  ros-lyrical-tf2-ros-py
BuildRequires:  ros-lyrical-yasmin
BuildRequires:  ros-lyrical-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  python%{python3_pkgversion}-pytest-cov
BuildRequires:  ros-lyrical-ament-cmake-gtest
BuildRequires:  ros-lyrical-ament-cmake-pytest
%endif

%description
YASMIN (Yet Another State MachINe) for ROS 2

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lyrical/setup.sh" ]; then . "/opt/ros/lyrical/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/lyrical" \
    -DAMENT_PREFIX_PATH="/opt/ros/lyrical" \
    -DCMAKE_PREFIX_PATH="/opt/ros/lyrical" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lyrical/setup.sh" ]; then . "/opt/ros/lyrical/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lyrical/setup.sh" ]; then . "/opt/ros/lyrical/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/lyrical

%changelog
* Sun Jul 26 2026 Miguel Ángel González Santamarta <mgons@unileon.es> - 6.1.0-1
- Autogenerated by Bloom

