%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/lyrical/.*$
%global __requires_exclude_from ^/opt/ros/lyrical/.*$

Name:           ros-lyrical-yasmin-cli
Version:        6.1.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS yasmin_cli package

License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lyrical-ament-index-python
Requires:       ros-lyrical-rclpy
Requires:       ros-lyrical-ros2cli
Requires:       ros-lyrical-yasmin
Requires:       ros-lyrical-yasmin-editor
Requires:       ros-lyrical-yasmin-factory
Requires:       ros-lyrical-yasmin-plugins-manager
Requires:       ros-lyrical-yasmin-viewer
Requires:       ros-lyrical-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-lyrical-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
CLI tools for inspecting YASMIN states and metadata.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lyrical/setup.sh" ]; then . "/opt/ros/lyrical/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lyrical/setup.sh" ]; then . "/opt/ros/lyrical/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/lyrical"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lyrical/setup.sh" ]; then . "/opt/ros/lyrical/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/lyrical

%changelog
* Sun Jul 26 2026 Maik Knof <maik.knof@gmx.de> - 6.1.0-1
- Autogenerated by Bloom

