name: Humble Docker Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  humble_docker_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker
        uses: docker/build-push-action@v6
        with:
          build-args: ROS_DISTRO=humble
          push: true
          tags: mgons/yasmin:humble
